2025-05-25 10:32:19,954 [ERROR] in __init__: URL: http://127.0.0.1:8080/home
2025-05-25 10:32:19,959 [ERROR] in __init__: Payload: {"block_id": "71", "block_name": "Singanamala", "district_id": "3", "district_name": "Ananthapuramu", "district_short_name": "ANA", "panchayat_id": "1529", "panchayat_name": "Lolur"}
2025-05-25 12:26:09,342 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iAndhra/app/routes/mobile.py", line 435, in print
    return render_template('mobile/print.html',village_count=village_count,tga=round(tga,2),human_data=human,human=json.dumps(human),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grove/GitHub/iAndhra/app/templates/mobile/print.html", line 555, in top-level template code
    <td class="text-end py-0">{{row.primary|indian_format}}</td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iAndhra/app/classes/helper.py", line 155, in indian_number_format
    is_negative = value < 0
                  ^^^^^^^^^
TypeError: '<' not supported between instances of 'dict' and 'int'
2025-05-25 12:26:09,351 [ERROR] in __init__: URL: http://127.0.0.1:8080/print
2025-05-25 12:26:09,354 [ERROR] in __init__: Payload: {"block_id": "71", "block_name": "Singanamala", "district_id": "3", "district_name": "Ananthapuramu", "district_short_name": "ANA", "panchayat_id": "1537", "panchayat_name": "Tarimela"}
